import{BASE,API,field,numberField,esc,textField,doubleField,stamp,apiFetch,authInit,uid}from'./config.js';
const KEY='safar_passenger_ride';let rideName=localStorage.getItem(KEY),poll=null,map=null,marker=null;
const $=id=>document.getElementById(id);const labels={requested:'در انتظار راننده',accepted:'راننده سفر را قبول کرد',started:'سفر در حال انجام است',completed:'سفر پایان یافت',cancelled:'سفر لغو شد'};
function message(t,c=''){ $('msg').textContent=t;$('msg').className='status '+c }
function initMap(){if(!window.L||!$('map'))return;map=L.map('map').setView([34.5553,69.2075],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map)}
function setMap(lat,lng,label='موقعیت'){if(!map)return;const p=[Number(lat),Number(lng)];if(!Number.isFinite(p[0])||!Number.isFinite(p[1]))return;map.setView(p,15);if(marker)marker.setLatLng(p);else marker=L.marker(p).addTo(map);marker.bindPopup(label).openPopup()}
function render(f){const s=field(f.status);$('rideBox').innerHTML=`<div class="ride"><div class="row"><b>وضعیت</b><b>${esc(labels[s]||s)}</b></div><div class="row"><span>مبدا</span><span>${esc(field(f.from))}</span></div><div class="row"><span>مقصد</span><span>${esc(field(f.to))}</span></div><div class="row"><span>کرایه</span><span>${numberField(f.fare)} افغانی</span></div>${field(f.driverName)?`<div class="row"><span>راننده</span><span>${esc(field(f.driverName))}</span></div>`:''}${field(f.driverPlate)?`<div class="row"><span>پلاک</span><span>${esc(field(f.driverPlate))}</span>`:''}${s==='requested'?'<button id="cancel" class="dangerBtn">لغو درخواست</button>':''}</div>`;$('current').style.display='block';$('cancel')?.addEventListener('click',cancelRide)}
async function getRide(){if(!rideName)return null;const r=await apiFetch(`${BASE}/${encodeURIComponent(rideName)}?key=${API}`);if(!r.ok)return null;return await r.json()}
async function getDriver(id){const r=await apiFetch(`${BASE}/drivers/${encodeURIComponent(id)}?key=${API}`);return r.ok?await r.json():null}
async function loadRide(){if(!rideName)return;try{const j=await getRide();if(!j)return;render(j.fields||{});const s=field(j.fields?.status),did=field(j.fields?.driverId);if(did){try{const d=await getDriver(did),df=d?.fields||{};if(df.lat?.doubleValue!==undefined)setMap(df.lat.doubleValue,df.lng.doubleValue,'راننده');}catch(e){}}if(['completed','cancelled'].includes(s)){clearInterval(poll);$('request').disabled=false}}catch(e){}}
async function create(){await authInit();const name=$('name').value.trim(),phone=$('phone').value.trim(),from=$('from').value.trim(),to=$('to').value.trim(),fare=Number($('fare').value||0);if(!name||!phone||!from||!to){message('نام، شماره، مبدا و مقصد را کامل وارد کنید.','err');return}if(fare<=0){message('کرایه باید بیشتر از صفر باشد.','err');return}$('request').disabled=true;message('در حال ثبت درخواست در سرور...');const body={fields:{passengerId:textField(uid()),passengerName:textField(name),phone:textField(phone),from:textField(from),to:textField(to),fare:doubleField(fare),status:textField('requested'),createdAt:stamp()}};try{const r=await apiFetch(`${BASE}/rides?key=${API}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)throw Error(j?.error?.message||'خطای Firestore');rideName=j.name;localStorage.setItem(KEY,rideName);message('✅ سفر ثبت شد. منتظر راننده بمانید.','ok');render(j.fields);if(poll)clearInterval(poll);poll=setInterval(loadRide,4000)}catch(e){message('❌ ثبت نشد: '+e.message,'err');$('request').disabled=false}}
async function cancelRide(){if(!rideName)return;try{const r=await apiFetch(`${BASE}/${encodeURIComponent(rideName)}?updateMask.fieldPaths=status&key=${API}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({fields:{status:textField('cancelled')}})});if(!r.ok)throw Error();message('درخواست سفر لغو شد.','ok');localStorage.removeItem(KEY);rideName=null;clearInterval(poll);$('current').style.display='none';$('request').disabled=false}catch(e){message('لغو سفر انجام نشد.','err')}}
$('locate').onclick=()=>{if(!navigator.geolocation){message('موقعیت مکانی در دسترس نیست.','err');return}navigator.geolocation.getCurrentPosition(pos=>{const{latitude,longitude}=pos.coords;setMap(latitude,longitude,'مبدا شما');$('from').value=`موقعیت من (${latitude.toFixed(5)}, ${longitude.toFixed(5)})`},()=>message('اجازه دسترسی به موقعیت داده نشد.','err'),{enableHighAccuracy:true,timeout:10000})};authInit().catch(e=>message('❌ Firebase Auth فعال نیست: '+e.message,'err'));initMap();$('request').onclick=create;if(rideName){loadRide();poll=setInterval(loadRide,4000)}
